<script setup lang="ts">
import { MoreHorizontal } from 'lucide-vue-next'
import { AdminButton, AdminDataTable, AdminPagination, StatusPill } from '@super-admin/ui'
import type { UserRecord, UserStatus } from '../users.types'

const props = withDefaults(
  defineProps<{
    users: UserRecord[]
    total: number
    page: number
    pageSize: number
    state: 'idle' | 'loading' | 'empty' | 'error'
    density: 'compact' | 'comfortable'
    visibleColumns: string[]
  }>(),
  {
    users: () => [],
    total: 0
  }
)

const emit = defineEmits<{
  edit: [user: UserRecord]
  pageChange: [page: number]
  retry: []
}>()

function isVisible(column: string): boolean {
  return props.visibleColumns.includes(column)
}

function statusTone(status: UserStatus): 'neutral' | 'success' | 'warning' | 'danger' {
  if (status === 'active') {
    return 'success'
  }
  if (status === 'review') {
    return 'warning'
  }
  return 'neutral'
}

function statusLabel(status: UserStatus): string {
  if (status === 'active') {
    return 'Active'
  }
  if (status === 'review') {
    return 'Review'
  }
  return 'Paused'
}
</script>

<template>
  <AdminDataTable
    :state="state"
    :density="density"
    :column-count="visibleColumns.length + 1"
    empty-title="No users match this view"
    empty-description="Try a different search, filter, or preview scenario."
    error-title="Unable to load users"
    error-description="This error is generated by the mock API scenario."
  >
    <template #head>
      <tr>
        <th v-if="isVisible('name')" class="px-3 py-3 font-medium">Name</th>
        <th v-if="isVisible('email')" class="px-3 py-3 font-medium">Email</th>
        <th v-if="isVisible('role')" class="px-3 py-3 font-medium">Role</th>
        <th v-if="isVisible('region')" class="px-3 py-3 font-medium">Region</th>
        <th v-if="isVisible('status')" class="px-3 py-3 font-medium">Status</th>
        <th class="w-12 px-3 py-3 font-medium"><span class="sr-only">Actions</span></th>
      </tr>
    </template>
    <template #error-action>
      <AdminButton size="sm" @click="emit('retry')">Retry</AdminButton>
    </template>
    <tr v-for="user in users" :key="user.id" class="border-t border-[var(--border)] bg-[var(--surface)]">
      <td v-if="isVisible('name')" class="px-3 text-[var(--foreground)]" :class="density === 'compact' ? 'py-2' : 'py-3'">
        <div class="font-medium">{{ user.name }}</div>
        <div class="text-xs text-[var(--muted-foreground)]">{{ user.id }}</div>
      </td>
      <td v-if="isVisible('email')" class="px-3 text-[var(--muted-foreground)]" :class="density === 'compact' ? 'py-2' : 'py-3'">
        {{ user.email }}
      </td>
      <td v-if="isVisible('role')" class="px-3 text-[var(--muted-foreground)]" :class="density === 'compact' ? 'py-2' : 'py-3'">
        {{ user.role }}
      </td>
      <td v-if="isVisible('region')" class="px-3 text-[var(--muted-foreground)]" :class="density === 'compact' ? 'py-2' : 'py-3'">
        {{ user.region }}
      </td>
      <td v-if="isVisible('status')" class="px-3" :class="density === 'compact' ? 'py-2' : 'py-3'">
        <StatusPill :label="statusLabel(user.status)" :tone="statusTone(user.status)" />
      </td>
      <td class="px-3" :class="density === 'compact' ? 'py-2' : 'py-3'">
        <AdminButton size="icon" variant="ghost" :title="`Edit ${user.name}`" @click="emit('edit', user)">
          <MoreHorizontal class="size-4" />
        </AdminButton>
      </td>
    </tr>
  </AdminDataTable>
  <AdminPagination :page="page" :page-size="pageSize" :total="total" @page-change="emit('pageChange', $event)" />
</template>
