import type { NormalizedStarterGenerationInput } from './parse-args.js'
import { SUPPORTED_NODE_RANGE } from './runtime-contract.js'

export function createReadme(input: NormalizedStarterGenerationInput): string {
  const qualityCommands =
    input.quality === 'standard'
      ? `${input.packageManager} run lint
${input.packageManager} run test
${input.packageManager} run check
`
      : ''
  const examplesSection = input.examples.included
    ? `## Remove Examples

Examples 是完整的可删除功能切片：

1. 删除 \`src/modules/examples/\`、\`access/\`、\`dashboard/\`、\`users/\`、\`workbench/\`，以及对应的 \`src/api/*.api.ts\` 和 \`src/api/mock/*.mock.ts\`。
2. 从 \`src/modules/module-registry.ts\` 删除指向 \`src/modules/examples/examples.registration.ts\` 的 \`examplesRegistration\` import 和 registration entry。
3. 同步更新 \`ai-context/extension-points.md\`：移除 \`src/modules/examples/examples.manifest.ts\`、\`src/modules/examples/examples.registration.ts\` 和“删除 Examples”任务说明，记录 Examples 已省略。
4. 如果生成了 ECharts，同时删除 \`src/modules/charts/\`、\`src/shared/charts/\`、\`echarts\` / \`vue-echarts\` 依赖和 \`ai-context/charts.md\`。
5. 运行 \`${input.packageManager} run check\`；minimal 项目改为运行 typecheck 与 build。

删除后默认入口自动使用第一个剩余模块；如果没有注册任何模块，则进入 \`/workspace\`。
`
    : `## Examples

Examples were omitted at generation time with \`--no-examples\`. Add business modules directly through \`src/modules/module-registry.ts\`.
`

  return `# ${input.projectName}

Super Admin starter project generated by \`create-super-admin\`.

## Runtime

- Node.js: \`${SUPPORTED_NODE_RANGE}\`

## Scripts

\`\`\`bash
${input.packageManager} install
${input.packageManager} run dev
${qualityCommands}${input.packageManager} run typecheck
${input.packageManager} run build
\`\`\`

${examplesSection}
## Guide

- AI 协作上下文：先读 \`AGENTS.md\`；Claude Code 会通过 \`CLAUDE.md\` 导入同一入口。
${input.examples.included ? '- 删除示例、连接 API、扩展质量工具：查看 Super Admin 文档。' : '- 连接 API、扩展模块和质量工具：查看 Super Admin 文档。'}
- 修改主题：编辑 \`super-admin.config.ts\` 和 \`src/super-admin/theme-registry.generated.ts\`。
- 修改语言：编辑 \`src/i18n/\`。
- 图表模板：选择 ECharts 时会在 Examples 下生成图表案例、\`src/modules/charts/\` 和主题适配的 ECharts helper；未选择时不会安装图表依赖。
`
}
