import type { StarterGenerationInput } from './parse-args.js'
import { superAdminPackageVersionRanges } from './package-version-ranges.generated.js'
import { themeDefinitions } from './theme-options.js'
import type { StarterLocaleId, StarterThemeId } from './theme-options.js'

type SuperAdminPackageName = keyof typeof superAdminPackageVersionRanges

export type CreatePackageJsonOptions = {
  packageVersionRanges?: Partial<Record<SuperAdminPackageName, string>>
}

function formatStringList(values: readonly string[]): string {
  return values.map((value) => `'${value}'`).join(', ')
}

function formatTypeUnion(values: readonly string[]): string {
  return values.map((value) => `'${value}'`).join(' | ')
}

function getLocaleI18nKey(locale: StarterLocaleId): string {
  return locale === 'zh-CN' ? 'zhCN' : 'enUS'
}

export function createPackageJson(input: StarterGenerationInput, options: CreatePackageJsonOptions = {}): string {
  const versionRanges = {
    ...superAdminPackageVersionRanges,
    ...(options.packageVersionRanges ?? {})
  }
  const dependencies: Record<string, string> = {
    '@super-admin-org/core': versionRanges['@super-admin-org/core'],
    '@super-admin-org/theme': versionRanges['@super-admin-org/theme'],
    '@super-admin-org/ui': versionRanges['@super-admin-org/ui'],
    '@tanstack/vue-query': '^5.0.0',
    '@lucide/vue': '^1.18.0',
    'motion-v': '^2.3.0',
    pinia: '^3.0.0',
    vue: '^3.5.0',
    'vue-i18n': '^11.4.4',
    'vue-router': '^4.5.0'
  }

  if (input.charts.provider === 'echarts') {
    dependencies.echarts = '^6.1.0'
    dependencies['vue-echarts'] = '^8.0.1'
  }

  for (const themeId of input.themes.installed) {
    const packageName = themeDefinitions[themeId].packageName
    dependencies[packageName] = versionRanges[packageName as SuperAdminPackageName]
  }

  return `${JSON.stringify(
    {
      name: input.packageName,
      version: '0.0.0',
      private: true,
      type: 'module',
      scripts: {
        dev: 'vite',
        build: 'vue-tsc --noEmit && vite build',
        typecheck: 'vue-tsc --noEmit',
        preview: 'vite preview'
      },
      dependencies,
      devDependencies: {
        '@tailwindcss/vite': '^4.0.0',
        '@vitejs/plugin-vue': '^6.0.0',
        '@vue/tsconfig': '^0.8.0',
        tailwindcss: '^4.0.0',
        typescript: '^5.0.0',
        vite: '^8.0.0',
        'vue-tsc': '^3.0.0'
      }
    },
    null,
    2
  )}\n`
}

export function createIndexHtml(projectName: string): string {
  return `<!doctype html>
<html lang="zh-CN">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName}</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
`
}

export function createViteConfig(): string {
  return `import { fileURLToPath, URL } from 'node:url'
import tailwindcss from '@tailwindcss/vite'
import vue from '@vitejs/plugin-vue'
import { defineConfig } from 'vite'

export default defineConfig({
  plugins: [vue(), tailwindcss()],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  }
})
`
}

export function createTsconfig(): string {
  return `${JSON.stringify(
    {
      extends: '@vue/tsconfig/tsconfig.dom.json',
      compilerOptions: {
        baseUrl: '.',
        lib: ['ES2022', 'DOM', 'DOM.Iterable'],
        paths: {
          '@/*': ['src/*']
        },
        target: 'ES2022',
        strict: true,
        noEmit: true,
        types: ['vite/client']
      },
      include: ['super-admin.config.ts', 'src/**/*.ts', 'src/**/*.vue', 'src/**/*.d.ts']
    },
    null,
    2
  )}\n`
}

export function createReadme(projectName: string, packageManager: string): string {
  return `# ${projectName}

Super Admin starter project generated by \`create-super-admin\`.

## Scripts

\`\`\`bash
${packageManager} install
${packageManager} run dev
${packageManager} run typecheck
${packageManager} run build
\`\`\`

## Guide

- 删除示例、连接 API、添加测试或 lint：查看 Super Admin 文档。
- 修改主题：编辑 \`super-admin.config.ts\` 和 \`src/super-admin/theme-registry.generated.ts\`。
- 修改语言：编辑 \`src/i18n/\`。
- 图表模板：选择 ECharts 时会在 Examples 下生成图表案例、\`src/modules/charts/\` 和主题适配的 ECharts helper；未选择时不会安装图表依赖。
`
}

export function createSuperAdminConfig(input: StarterGenerationInput): string {
  return `export default {
  themes: {
    installed: [${formatStringList(input.themes.installed)}],
    default: '${input.themes.default}',
    switcher: '${input.themes.installed.length > 1 ? 'auto' : 'off'}'
  },
  i18n: {
    installed: [${formatStringList(input.i18n.installed)}],
    defaultLocale: '${input.i18n.default}',
    switcher: ${String(input.i18n.switcher)}
  },
  charts: {
    provider: '${input.charts.provider}'
  }
} as const
`
}

export function createThemeRegistry(themes: StarterThemeId[], defaultTheme: StarterThemeId): string {
  const imports = themes
    .map((themeId) => {
      const definition = themeDefinitions[themeId]
      return `import { ${definition.profileExport} } from '${definition.packageName}'`
    })
    .join('\n')
  const profileExports = themes.map((themeId) => themeDefinitions[themeId].profileExport)
  const fallbackProfile = themeDefinitions[defaultTheme].profileExport

  return `import type { DesignProfile, DesignProfileId } from '@super-admin-org/core'
${imports}

export const builtInDesignProfiles = [${profileExports.join(', ')}] as const

export function getBuiltInDesignProfile(profileId: DesignProfileId): DesignProfile {
  return builtInDesignProfiles.find((profile) => profile.id === profileId) ?? ${fallbackProfile}
}
`
}

export function createEnvDts(): string {
  return `declare module '*.vue' {
  import type { DefineComponent } from 'vue'

  const component: DefineComponent<object, object, unknown>
  export default component
}

interface ImportMetaEnv {
  readonly VITE_SUPER_ADMIN_ASSISTANT_ENDPOINT?: string
}

interface ImportMeta {
  readonly env: ImportMetaEnv
}

import type { PageShellMeta } from '@super-admin-org/core'

declare module 'vue-router' {
  interface RouteMeta extends Partial<PageShellMeta> {
    authLayout?: boolean
    workspaceTitle?: string
  }
}
`
}

export function createUsersApi(): string {
  return `import { createPageListResult } from '@super-admin-org/core'
import { mockUsers } from '@/api/mock/users.mock'
import type { MockUser } from '@/api/mock/users.mock'
import type { UserListParams, UserListResult, UserRecord } from '@/modules/users/users.types'

const LOADING_DELAY_MS = 700

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => {
    setTimeout(resolve, ms)
  })
}

function matchesKeyword(user: UserRecord, keyword: string): boolean {
  const term = keyword.trim().toLowerCase()
  if (!term) {
    return true
  }

  return [user.name, user.email, user.role, user.status, user.region].some((value) => value.toLowerCase().includes(term))
}

function normalizeUser(user: MockUser): UserRecord {
  return {
    id: user.userId,
    name: user.displayName,
    email: user.emailAddress,
    role: user.roleName,
    status: user.state,
    region: user.regionName,
    notes: user.profileNotes
  }
}

function filterUsers(params: UserListParams): UserRecord[] {
  return mockUsers.map(normalizeUser).filter((user) => {
    const matchesStatus = params.status === 'all' || user.status === params.status

    return matchesStatus && matchesKeyword(user, params.keyword ?? '')
  })
}

export async function listUsers(params: UserListParams): Promise<UserListResult> {
  if (params.scenario === 'error') {
    throw new Error('Unable to load users')
  }

  if (params.scenario === 'loading') {
    await delay(LOADING_DELAY_MS)
  }

  const filteredUsers = params.scenario === 'empty' ? [] : filterUsers(params)
  const start = (params.page - 1) * params.pageSize
  const end = start + params.pageSize

  return createPageListResult(filteredUsers.slice(start, end), filteredUsers.length, params)
}
`
}

export function createAuthTypes(): string {
  return `export type AuthFieldErrors<Field extends string = string> = Partial<Record<Field, string>>

export type LoginInput = {
  email: string
  password: string
}

export type RegisterInput = {
  name: string
  email: string
  organization: string
  password: string
}

export type AuthUser = {
  email: string
  id: string
  name: string
  role: string
}

export type AuthSession = {
  permissions: string[]
  token: string
  tokenType: 'Bearer'
  user: AuthUser
}
`
}

export function createAuthSession(): string {
  return `import type { AuthSession } from './auth.types'

export function createTemplateAuthSession(): AuthSession {
  return {
    permissions: ['users:read'],
    token: 'template-session-token',
    tokenType: 'Bearer',
    user: {
      email: 'mira.owner@example.com',
      id: 'template-user',
      name: 'Mira Chen',
      role: 'Owner'
    }
  }
}
`
}

export function createAuthSessionStore(): string {
  return `import { defineStore } from 'pinia'
import { computed, shallowRef } from 'vue'
import type { AuthSession } from '@/modules/auth/auth.types'

const STORAGE_KEY = 'super-admin:auth-session'

function getStorage(): Storage | null {
  return typeof window === 'undefined' ? null : window.localStorage
}

export const useAuthSessionStore = defineStore('authSession', () => {
  const session = shallowRef<AuthSession | null>(null)

  const isAuthenticated = computed(() => session.value !== null)
  const authorizationHeader = computed(() => (session.value ? \`\${session.value.tokenType} \${session.value.token}\` : undefined))
  const currentUser = computed(() => session.value?.user ?? null)

  function setTemplateSession(nextSession: AuthSession): void {
    session.value = nextSession
    getStorage()?.removeItem(STORAGE_KEY)
  }

  function clearSession(): void {
    session.value = null
    getStorage()?.removeItem(STORAGE_KEY)
  }

  return {
    authorizationHeader,
    clearSession,
    currentUser,
    isAuthenticated,
    session,
    setTemplateSession
  }
})
`
}

export function createLoginPage(): string {
  return `<script setup lang="ts">
import { ArrowRight, KeyRound } from '@lucide/vue'
import { computed, reactive, shallowRef } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { AdminAlert, AdminButton, AdminField, AdminTextInput, AdminValidationSummary } from '@super-admin-org/ui'
import { resolvePostLoginPath } from '@/router/auth-guard'
import { useAuthSessionStore } from '@/stores/auth-session.store'
import { createTemplateAuthSession } from './auth-session'
import AuthLayout from './components/AuthLayout.vue'
import { validateLoginInput } from './auth.validation'
import type { AuthFieldErrors, LoginInput } from './auth.types'

const router = useRouter()
const route = useRoute()
const { t } = useI18n()
const session = useAuthSessionStore()
const form = reactive<LoginInput>({
  email: 'mira.owner@example.com',
  password: 'reference-admin'
})
const fieldErrors = shallowRef<AuthFieldErrors<keyof LoginInput>>({})
const submitError = shallowRef('')
const isSubmitting = shallowRef(false)

const validationMessages = computed(() => Object.values(fieldErrors.value).filter((message) => message !== undefined))

async function submitLogin(): Promise<void> {
  fieldErrors.value = validateLoginInput(form, t)
  submitError.value = ''

  if (Object.keys(fieldErrors.value).length > 0) {
    return
  }

  isSubmitting.value = true

  try {
    session.setTemplateSession(createTemplateAuthSession())
    await router.push(resolvePostLoginPath(route.query.redirect))
  } catch (error) {
    submitError.value = error instanceof Error ? error.message : t('auth.login.unableToSignIn')
  } finally {
    isSubmitting.value = false
  }
}
</script>

<template>
  <AuthLayout
    :eyebrow="t('auth.login.eyebrow')"
    :title="t('auth.login.title')"
    :description="t('auth.login.description')"
  >
    <div class="grid gap-5">
      <div>
        <div class="inline-flex size-11 items-center justify-center rounded-[var(--radius-md)] border border-[var(--border)] bg-[var(--surface-sunken)] text-[var(--primary)] shadow-[var(--glow)]">
          <KeyRound class="size-5" />
        </div>
        <h2 class="mt-4 [font-family:var(--font-display)] text-3xl leading-tight">{{ t('auth.login.heading') }}</h2>
        <p class="mt-2 text-sm leading-6 text-[var(--muted-foreground)]">
          {{ t('auth.login.intro') }}
        </p>
      </div>

      <AdminAlert
        v-if="submitError"
        tone="danger"
        :title="t('auth.login.failedTitle')"
        :description="submitError"
      />

      <AdminValidationSummary :title="t('common.primitives.validationTitle')" :errors="validationMessages" />

      <form class="grid gap-4" @submit.prevent="submitLogin">
        <AdminField :label="t('auth.login.email')" for="auth-email" required :required-label="t('validation.requiredLabel')" :error="fieldErrors.email">
          <AdminTextInput id="auth-email" v-model="form.email" type="email" :invalid="Boolean(fieldErrors.email)" autocomplete="email" />
        </AdminField>

        <AdminField :label="t('auth.login.password')" for="auth-password" required :required-label="t('validation.requiredLabel')" :error="fieldErrors.password">
          <AdminTextInput id="auth-password" v-model="form.password" type="password" :invalid="Boolean(fieldErrors.password)" autocomplete="current-password" />
        </AdminField>

        <AdminButton type="submit" variant="primary" :disabled="isSubmitting" class="w-full">
          <span>{{ isSubmitting ? t('auth.login.submitting') : t('auth.login.submit') }}</span>
          <ArrowRight class="size-4" />
        </AdminButton>
      </form>

      <div class="grid gap-2 rounded-[var(--radius-md)] border border-[var(--border)] bg-[var(--surface-sunken)] p-3 text-xs text-[var(--muted-foreground)]">
        <div class="flex items-center justify-between gap-3">
          <span>{{ t('auth.login.referenceEmail') }}</span>
          <span class="text-[var(--foreground)]">mira.owner@example.com</span>
        </div>
        <div class="flex items-center justify-between gap-3">
          <span>{{ t('auth.login.referencePassword') }}</span>
          <span class="text-[var(--foreground)]">reference-admin</span>
        </div>
      </div>

      <p class="text-center text-sm text-[var(--muted-foreground)]">
        {{ t('auth.login.onboardingQuestion') }}
        <RouterLink class="text-[var(--primary)] underline-offset-4 hover:underline" to="/auth/register">{{ t('auth.login.createAccount') }}</RouterLink>
      </p>
    </div>
  </AuthLayout>
</template>
`
}

export function createI18nIndex(locales: StarterLocaleId[]): string {
  const includeEnglish = locales.includes('en-US')
  const imports = includeEnglish ? "import enUS from './locales/en-US'\nimport zhCN from './locales/zh-CN'" : "import zhCN from './locales/zh-CN'"
  const messages = includeEnglish ? `  [DEFAULT_LOCALE]: zhCN,\n  [OPTIONAL_LOCALE]: enUS` : '  [DEFAULT_LOCALE]: zhCN'
  const optionalLocale = includeEnglish ? "\nexport const OPTIONAL_LOCALE = 'en-US'" : ''

  return `import { createI18n } from 'vue-i18n'
${imports}

export const DEFAULT_LOCALE = 'zh-CN'${optionalLocale}

export const messages = {
${messages}
} as const

export type Locale = keyof typeof messages
export type LocaleCatalog = Record<string, unknown>
export type MessageValues = Record<string, string | number>
export type MessageTranslator = (key: string, values?: MessageValues) => string

function flattenMessageKeys(value: unknown, prefix = ''): string[] {
  if (typeof value === 'string') {
    return [prefix]
  }

  if (typeof value !== 'object' || value === null) {
    return []
  }

  return Object.entries(value).flatMap(([key, child]) => {
    const nextPrefix = prefix ? \`\${prefix}.\${key}\` : key
    return flattenMessageKeys(child, nextPrefix)
  })
}

function hasMessageKey(value: unknown, path: string): boolean {
  return path.split('.').every((segment, index, segments) => {
    if (typeof value !== 'object' || value === null || !(segment in value)) {
      return false
    }

    value = (value as Record<string, unknown>)[segment]
    return index < segments.length - 1 || typeof value === 'string'
  })
}

export function resolveLocale(locale: string | undefined): Locale {
  return Object.hasOwn(messages, locale ?? '') ? (locale as Locale) : DEFAULT_LOCALE
}

export function findMissingLocaleKeys(source: LocaleCatalog, target: LocaleCatalog): string[] {
  return flattenMessageKeys(source).filter((key) => !hasMessageKey(target, key))
}

export function createAdminI18n(locale: Locale = DEFAULT_LOCALE) {
  return createI18n({
    fallbackLocale: DEFAULT_LOCALE,
    legacy: false,
    locale,
    messages,
    missing: (_locale, key) => key
  })
}

export const i18n = createAdminI18n()

export function getActiveLocale(adminI18n: ReturnType<typeof createAdminI18n> = i18n): Locale {
  const locale = adminI18n.global.locale
  return resolveLocale(typeof locale === 'string' ? locale : locale.value)
}

export function setActiveLocale(locale: Locale, adminI18n: ReturnType<typeof createAdminI18n> = i18n): void {
  adminI18n.global.locale.value = locale
}

export function createMessageTranslator(locale: Locale = DEFAULT_LOCALE): MessageTranslator {
  const localI18n = createAdminI18n(locale)
  return (key, values) => localI18n.global.t(key, values ?? {})
}

export const translateAdminMessage: MessageTranslator = (key, values) => i18n.global.t(key, values ?? {})
`
}

export function createCommandPaletteItems(locales: StarterLocaleId[], source: string): string {
  const localeType = formatTypeUnion(locales)
  const localeEntries = locales.map((locale) => `  '${locale}': '${getLocaleI18nKey(locale)}'`).join(',\n')
  const localeList = formatStringList(locales)

  return source
    .replace("type Locale = 'zh-CN' | 'en-US'", `type Locale = ${localeType}`)
    .replace(
      /const LOCALE_I18N_KEY: Record<Locale, string> = \{[\s\S]*?\n\}/,
      `const LOCALE_I18N_KEY: Record<Locale, string> = {\n${localeEntries}\n}`
    )
    .replace("    const locales: Locale[] = ['zh-CN', 'en-US']", `    const locales: Locale[] = [${localeList}]`)
}

export function createPreferencesStore(): string {
  return `import {
  defaultAiAvailability,
  mergeAppearanceState,
  type AiAvailability,
  type AppearanceState,
  type AppearanceStateInput,
  type ColorMode,
  type Density,
  type DesignProfileId,
  type LayoutPresetId,
  type ResolvedColorMode
} from '@super-admin-org/core'
import { defineStore } from 'pinia'
import { computed, reactive, shallowRef } from 'vue'
import superAdminConfig from '../../super-admin.config'
import { DEFAULT_LOCALE, resolveLocale, setActiveLocale, type Locale } from '@/i18n'

const STORAGE_KEY = 'super-admin:preferences'
const STAGE_MANAGER_DESKTOP_QUERY = '(min-width: 1280px)'
const installedProfiles: DesignProfileId[] = [...superAdminConfig.themes.installed]
const defaultProfile = superAdminConfig.themes.default

export type StageTransitionRect = {
  height: number
  left: number
  top: number
  width: number
}

export type StageTransitionGhost = {
  id: number
  source: StageTransitionRect
  status: 'measuring' | 'animating'
  target: StageTransitionRect
  title: string
}

function toStageTransitionRect(rect: DOMRect): StageTransitionRect {
  return {
    height: rect.height,
    left: rect.left,
    top: rect.top,
    width: rect.width
  }
}

function readStoredPreferences(): AppearanceStateInput {
  const raw = window.localStorage.getItem(STORAGE_KEY)
  if (!raw) {
    return {}
  }

  try {
    const parsed: unknown = JSON.parse(raw)
    return typeof parsed === 'object' && parsed !== null ? (parsed as AppearanceStateInput) : {}
  } catch {
    return {}
  }
}

function resolveProfileId(profileId: DesignProfileId | undefined): DesignProfileId {
  return profileId && installedProfiles.includes(profileId) ? profileId : defaultProfile
}

function createInitialAppearanceState(): AppearanceState {
  const state = mergeAppearanceState(readStoredPreferences())

  return {
    ...state,
    locale: resolveLocale(state.locale),
    profileId: resolveProfileId(state.profileId)
  }
}

export const usePreferencesStore = defineStore('preferences', () => {
  const state = reactive<AppearanceState>(createInitialAppearanceState())
  const systemMode = shallowRef<ResolvedColorMode>('dark')
  const providerMode = shallowRef<'mock' | 'custom'>('mock')
  const aiAvailability = shallowRef<AiAvailability>(defaultAiAvailability)
  const controlCenterOpen = shallowRef(false)
  const stageOverviewOpen = shallowRef(false)
  const stageManagerDesktopAvailable = shallowRef(false)
  const stageTransitionGhost = shallowRef<StageTransitionGhost | null>(null)
  const aiAssistantOpen = shallowRef(false)
  const commandPaletteOpen = shallowRef(false)

  const profileId = computed(() => state.profileId)
  const locale = computed(() => state.locale)
  const colorMode = computed(() => state.colorMode)
  const density = computed(() => state.density)
  const layoutPreset = computed(() => state.layoutPreset)
  const workspaceTabs = computed(() => state.workspaceTabs)
  const stageManager = computed(() => state.stageManager)
  const summary = computed(
    () => \`\${state.profileId} / \${state.colorMode} / \${state.layoutPreset}\`
  )

  function persist(): void {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(state))
  }

  setActiveLocale(resolveLocale(state.locale ?? DEFAULT_LOCALE))

  function setProfile(profileId: DesignProfileId): void {
    state.profileId = resolveProfileId(profileId)
    persist()
  }

  function setLocale(locale: Locale): void {
    state.locale = resolveLocale(locale)
    setActiveLocale(state.locale)
    persist()
  }

  function setColorMode(colorMode: ColorMode): void {
    state.colorMode = colorMode
    persist()
  }

  function setDensity(density: Density): void {
    state.density = density
    persist()
  }

  function setLayoutPreset(layoutPreset: LayoutPresetId): void {
    state.layoutPreset = layoutPreset
    persist()
  }

  function setTabsEnabled(enabled: boolean): void {
    state.workspaceTabs.enabled = enabled
    persist()
  }

  function setStageRailEnabled(enabled: boolean): void {
    state.stageManager.railEnabled = enabled
    persist()
  }

  function setStageManagerDesktopAvailable(available: boolean): void {
    stageManagerDesktopAvailable.value = available
    if (!available) {
      stageOverviewOpen.value = false
    }
  }

  function openControlCenter(): void {
    controlCenterOpen.value = true
  }

  function closeControlCenter(): void {
    controlCenterOpen.value = false
  }

  function openStageOverview(): void {
    if (!stageManagerDesktopAvailable.value) {
      return
    }

    controlCenterOpen.value = false
    stageOverviewOpen.value = true
  }

  function closeStageOverview(): void {
    stageOverviewOpen.value = false
  }

  function startStageTransition(sourceRect: DOMRect, title: string): void {
    const source = toStageTransitionRect(sourceRect)
    stageTransitionGhost.value = {
      id: Date.now(),
      source,
      status: 'measuring',
      target: source,
      title
    }
  }

  function finishStageTransition(targetRect: DOMRect): void {
    if (!stageTransitionGhost.value) {
      return
    }

    stageTransitionGhost.value = {
      ...stageTransitionGhost.value,
      status: 'animating',
      target: toStageTransitionRect(targetRect)
    }
  }

  function clearStageTransition(): void {
    stageTransitionGhost.value = null
  }

  function openAiAssistant(): void {
    aiAssistantOpen.value = true
  }

  function closeAiAssistant(): void {
    aiAssistantOpen.value = false
  }

  function openCommandPalette(): void {
    commandPaletteOpen.value = true
  }

  function closeCommandPalette(): void {
    commandPaletteOpen.value = false
  }

  function bindSystemColorMode(): void {
    const query = window.matchMedia('(prefers-color-scheme: dark)')
    const update = (): void => {
      systemMode.value = query.matches ? 'dark' : 'light'
    }
    update()
    query.addEventListener('change', update)
  }

  function bindStageManagerDesktopAvailability(): void {
    const query = window.matchMedia(STAGE_MANAGER_DESKTOP_QUERY)
    const update = (): void => setStageManagerDesktopAvailable(query.matches)
    update()
    query.addEventListener('change', update)
  }

  return {
    providerMode,
    aiAvailability,
    aiAssistantOpen,
    closeAiAssistant,
    closeCommandPalette,
    closeControlCenter,
    closeStageOverview,
    clearStageTransition,
    controlCenterOpen,
    commandPaletteOpen,
    finishStageTransition,
    openControlCenter,
    openAiAssistant,
    openCommandPalette,
    openStageOverview,
    stageManagerDesktopAvailable,
    stageOverviewOpen,
    stageTransitionGhost,
    systemMode,
    summary,
    profileId,
    locale,
    colorMode,
    density,
    layoutPreset,
    workspaceTabs,
    stageManager,
    bindStageManagerDesktopAvailability,
    bindSystemColorMode,
    setColorMode,
    setDensity,
    setLayoutPreset,
    setLocale,
    setProfile,
    setStageManagerDesktopAvailable,
    setTabsEnabled,
    setStageRailEnabled,
    startStageTransition
  }
})
`
}

export function createGlobalPreferences(options: { includeThemeSwitcher: boolean; includeLocaleSwitcher: boolean }): string {
  const themeImports = options.includeThemeSwitcher
    ? "  type DesignProfileId,\n"
    : ''
  const localeImport = options.includeLocaleSwitcher ? "import type { Locale } from '@/i18n'\n" : ''
  const registryImport = options.includeThemeSwitcher
    ? "import { builtInDesignProfiles } from '@/super-admin/theme-registry.generated'\n"
    : "import { getBuiltInDesignProfile } from '@/super-admin/theme-registry.generated'\n"
  const activeProfile = options.includeThemeSwitcher
    ? "const activeProfileName = computed(\n  () => builtInDesignProfiles.find((profile) => profile.id === preferences.profileId)?.name ?? preferences.profileId\n)"
    : "const activeProfileName = computed(() => getBuiltInDesignProfile(preferences.profileId).name)"
  const localeOptions = options.includeLocaleSwitcher
    ? "\nconst localeOptions = computed<{ id: Locale; label: string; detail: string }[]>(() => [\n  { id: 'zh-CN', label: t('shell.preferences.locales.zhCN.label'), detail: t('shell.preferences.locales.zhCN.detail') },\n  { id: 'en-US', label: t('shell.preferences.locales.enUS.label'), detail: t('shell.preferences.locales.enUS.detail') }\n])\n"
    : ''
  const selectProfile = options.includeThemeSwitcher
    ? "\nfunction selectProfile(profileId: DesignProfileId): void {\n  preferences.setProfile(profileId)\n}\n"
    : ''
  const selectLocale = options.includeLocaleSwitcher
    ? "\nfunction selectLocale(locale: Locale): void {\n  preferences.setLocale(locale)\n}\n"
    : ''
  const themeSection = options.includeThemeSwitcher
    ? `
              <div class="rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface-sunken)] p-4">
                <div class="flex items-center justify-between gap-3">
                  <div>
                    <h3 class="[font-family:var(--font-display)] text-lg">{{ t('shell.preferences.themeProfile') }}</h3>
                    <p class="text-xs text-[var(--muted-foreground)]">{{ t('shell.preferences.themeProfileDescription') }}</p>
                  </div>
                  <StatusPill :label="activeProfileName" />
                </div>
                <div class="mt-4 grid gap-2 sm:grid-cols-2">
                  <button
                    v-for="profile in builtInDesignProfiles"
                    :key="profile.id"
                    type="button"
                    class="rounded-[var(--radius-md)] border p-3 text-left transition focus-visible:shadow-[var(--focus-ring)] focus-visible:outline-none"
                    :class="profile.id === preferences.profileId ? 'border-[var(--border-strong)] bg-[var(--active-tab-background)]' : 'border-[var(--border)] bg-[var(--surface)] hover:border-[var(--border-strong)]'"
                    @click="selectProfile(profile.id)"
                  >
                    <span class="[font-family:var(--font-display)] text-base">{{ profile.name }}</span>
                    <p class="mt-2 line-clamp-2 text-xs text-[var(--muted-foreground)]">{{ profile.description }}</p>
                  </button>
                </div>
              </div>`
    : ''
  const localeSection = options.includeLocaleSwitcher
    ? `
                  <div>
                    <div class="flex items-center justify-between gap-3 pb-2">
                      <span class="text-sm">{{ t('shell.preferences.locale') }}</span>
                      <span class="text-[11px] text-[var(--muted-foreground)]">{{ t('shell.preferences.localeDescription') }}</span>
                    </div>
                    <div class="grid gap-2 rounded-[var(--radius-md)] border border-[var(--border)] bg-[var(--surface)] p-2 sm:grid-cols-2">
                      <button
                        v-for="localeOption in localeOptions"
                        :key="localeOption.id"
                        type="button"
                        class="rounded-[var(--radius-sm)] px-3 py-2 text-left transition focus-visible:shadow-[var(--focus-ring)] focus-visible:outline-none"
                        :class="localeOption.id === preferences.locale ? 'bg-[var(--primary)] text-[var(--primary-foreground)] shadow-[var(--glow)]' : 'text-[var(--muted-foreground)] hover:bg-[var(--surface-raised)]'"
                        @click="selectLocale(localeOption.id)"
                      >
                        <span class="block text-sm">{{ localeOption.label }}</span>
                        <span class="block text-[11px] opacity-75">{{ localeOption.detail }}</span>
                      </button>
                    </div>
                  </div>`
    : ''

  return `<script setup lang="ts">
import { X } from '@lucide/vue'
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import {
  builtInLayoutPresets,
  type ColorMode,
${themeImports}  type LayoutPresetId
} from '@super-admin-org/core'
import { AdminButton, AdminScrollArea, StatusPill } from '@super-admin-org/ui'
${registryImport}${localeImport}import { usePreferencesStore } from '@/stores/preferences.store'
import GlobalPreferencesTrigger from './GlobalPreferencesTrigger.vue'

const props = withDefaults(
  defineProps<{
    trigger?: 'floating' | 'auth' | 'none'
  }>(),
  {
    trigger: 'floating'
  }
)

const preferences = usePreferencesStore()
const { t } = useI18n()

const modeOptions = computed<{ id: ColorMode; label: string; detail: string }[]>(() => [
  { id: 'light', label: t('shell.preferences.modes.light.label'), detail: t('shell.preferences.modes.light.detail') },
  { id: 'dark', label: t('shell.preferences.modes.dark.label'), detail: t('shell.preferences.modes.dark.detail') },
  { id: 'system', label: t('shell.preferences.modes.system.label'), detail: t('shell.preferences.modes.system.detail') }
])
${localeOptions}
${activeProfile}
const activeModeName = computed(
  () => modeOptions.value.find((mode) => mode.id === preferences.colorMode)?.label ?? preferences.colorMode
)
const triggerTitle = computed(() =>
  props.trigger === 'auth'
    ? t('shell.preferences.open', { profile: activeProfileName.value, mode: activeModeName.value })
    : t('shell.preferences.title')
)
const triggerLabel = computed(() =>
  props.trigger === 'auth' ? \`\${activeProfileName.value} / \${activeModeName.value}\` : t('shell.preferences.title')
)
const showTrigger = computed(() => props.trigger !== 'none')
${selectProfile}
function selectMode(colorMode: ColorMode): void {
  preferences.setColorMode(colorMode)
}
${selectLocale}
function selectLayout(layoutPreset: LayoutPresetId): void {
  preferences.setLayoutPreset(layoutPreset)
}
</script>

<template>
  <div>
    <GlobalPreferencesTrigger
      v-if="showTrigger"
      :label="triggerLabel"
      :title="triggerTitle"
      @activate="preferences.openControlCenter()"
    />

    <Teleport to="body">
      <div v-if="preferences.controlCenterOpen" class="fixed inset-0 z-[80] grid place-items-center bg-black/45 p-3 backdrop-blur-sm sm:p-4" @keydown.esc="preferences.closeControlCenter()">
        <AdminScrollArea
          as="section"
          class="max-h-[min(92vh,calc(100vh-2rem))] w-full max-w-5xl overflow-hidden rounded-[var(--radius-lg)] border border-[var(--border-strong)] bg-[var(--surface)] shadow-[var(--panel-shadow)]"
          view-class="min-h-0"
          role="dialog"
          aria-modal="true"
          aria-labelledby="control-center-title"
        >
          <header class="sticky top-0 z-10 border-b border-[var(--border)] bg-[var(--header-background)] p-4 sm:p-5">
            <div class="flex items-start justify-between gap-4">
              <div>
                <div class="flex items-center gap-2">
                  <StatusPill :label="t('shell.preferences.live')" />
                  <span class="text-xs uppercase tracking-[0.18em] text-[var(--muted-foreground)]">{{ t('shell.preferences.title') }}</span>
                </div>
                <h2 id="control-center-title" class="mt-2 [font-family:var(--font-display)] text-xl text-[var(--foreground)] sm:text-2xl">
                  {{ t('shell.preferences.workspaceConfiguration', { profile: activeProfileName }) }}
                </h2>
                <p class="mt-1 text-sm text-[var(--muted-foreground)]">
                  {{ t('shell.preferences.immediateUpdate') }}
                </p>
              </div>
              <AdminButton variant="ghost" size="icon" :title="t('shell.preferences.close')" @click="preferences.closeControlCenter()">
                <X class="size-4" />
              </AdminButton>
            </div>
          </header>

          <div class="grid items-start gap-5 p-4 sm:p-5 md:grid-cols-[minmax(0,1fr)_minmax(0,1.15fr)]">
            <section class="grid gap-4">${themeSection}
              <div class="rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface-sunken)] p-4">
                <h3 class="[font-family:var(--font-display)] text-lg">{{ t('shell.preferences.displayMode') }}</h3>
                <div class="mt-4 grid gap-3">${localeSection}
                  <div class="grid gap-2 rounded-[var(--radius-md)] border border-[var(--border)] bg-[var(--surface)] p-2 sm:grid-cols-3">
                    <button
                      v-for="mode in modeOptions"
                      :key="mode.id"
                      type="button"
                      class="rounded-[var(--radius-sm)] px-3 py-2 text-left transition focus-visible:shadow-[var(--focus-ring)] focus-visible:outline-none"
                      :class="mode.id === preferences.colorMode ? 'bg-[var(--primary)] text-[var(--primary-foreground)] shadow-[var(--glow)]' : 'text-[var(--muted-foreground)] hover:bg-[var(--surface-raised)]'"
                      @click="selectMode(mode.id)"
                    >
                      <span class="block text-sm">{{ mode.label }}</span>
                      <span class="block text-[11px] opacity-75">{{ mode.detail }}</span>
                    </button>
                  </div>
                </div>
              </div>
            </section>

            <section class="grid gap-4">
              <div class="rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface-sunken)] p-4">
                <h3 class="[font-family:var(--font-display)] text-lg">{{ t('shell.preferences.layout') }}</h3>
                <p class="text-xs text-[var(--muted-foreground)]">{{ t('shell.preferences.layoutDescription') }}</p>
                <div class="mt-4 grid gap-3 xl:grid-cols-3">
                  <button
                    v-for="layout in builtInLayoutPresets"
                    :key="layout.id"
                    type="button"
                    class="rounded-[var(--radius-md)] border bg-[var(--surface)] p-3 text-left transition focus-visible:shadow-[var(--focus-ring)] focus-visible:outline-none"
                    :class="layout.id === preferences.layoutPreset ? 'border-[var(--border-strong)] shadow-[var(--glow)]' : 'border-[var(--border)] hover:border-[var(--border-strong)]'"
                    @click="selectLayout(layout.id)"
                  >
                    <div :data-layout-preview="layout.id" class="grid h-24 gap-1 rounded-[var(--radius-sm)] border border-[var(--border)] bg-[var(--surface-sunken)] p-2">
                      <template v-if="layout.id === 'tri-column'">
                        <div class="grid h-full gap-1" style="grid-template-columns: 0.35fr 0.8fr 1.8fr 0.9fr;">
                          <span class="rounded-[var(--radius-xs)] bg-[var(--primary)]" />
                          <span class="rounded-[var(--radius-xs)] bg-[var(--surface-raised)]" />
                          <span class="rounded-[var(--radius-xs)] bg-[var(--accent)] opacity-60" />
                          <span class="rounded-[var(--radius-xs)] bg-[var(--surface-raised)]" />
                        </div>
                      </template>
                      <template v-else-if="layout.id === 'dual-column'">
                        <div class="grid h-full gap-1" style="grid-template-columns: 1fr 2fr;">
                          <span class="rounded-[var(--radius-xs)] bg-[var(--surface-raised)]" />
                          <span class="rounded-[var(--radius-xs)] bg-[var(--accent)] opacity-60" />
                        </div>
                      </template>
                      <template v-else>
                        <div class="grid h-full gap-1" style="grid-template-rows: 0.45fr 0.55fr 2fr;">
                          <span class="rounded-[var(--radius-xs)] bg-[var(--primary)]" />
                          <span class="rounded-[var(--radius-xs)] bg-[var(--surface-raised)]" />
                          <span class="rounded-[var(--radius-xs)] bg-[var(--accent)] opacity-60" />
                        </div>
                      </template>
                    </div>
                    <div class="mt-3 [font-family:var(--font-display)] text-base">{{ layout.name }}</div>
                    <p class="mt-1 line-clamp-2 text-xs text-[var(--muted-foreground)]">{{ layout.description }}</p>
                  </button>
                </div>
              </div>

              <div class="rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface-sunken)] p-4">
                <div class="flex items-center justify-between gap-3">
                  <div>
                    <h3 class="[font-family:var(--font-display)] text-lg">{{ t('shell.preferences.workspace') }}</h3>
                    <p class="text-xs text-[var(--muted-foreground)]">{{ t('shell.preferences.workspaceDescription') }}</p>
                  </div>
                  <StatusPill :label="t('shell.preferences.keepAlive')" tone="success" />
                </div>
                <div class="mt-4 grid gap-3 sm:grid-cols-2">
                  <button
                    type="button"
                    class="rounded-[var(--radius-md)] border p-3 text-left transition focus-visible:shadow-[var(--focus-ring)] focus-visible:outline-none"
                    :class="preferences.workspaceTabs.enabled ? 'border-[var(--border-strong)] bg-[var(--active-tab-background)] text-[var(--foreground)]' : 'border-[var(--border)] bg-[var(--surface)] text-[var(--muted-foreground)] hover:border-[var(--border-strong)] hover:text-[var(--foreground)]'"
                    @click="preferences.setTabsEnabled(!preferences.workspaceTabs.enabled)"
                  >
                    <span class="flex items-center justify-between gap-3">
                      <span class="text-sm">{{ t('shell.preferences.workspaceTabs') }}</span>
                      <span class="rounded-full border border-[var(--border)] px-2 py-0.5 text-[10px]">
                        {{ preferences.workspaceTabs.enabled ? t('shell.preferences.on') : t('shell.preferences.off') }}
                      </span>
                    </span>
                    <span class="mt-2 block text-[11px] opacity-75">{{ t('shell.preferences.tabsDescription') }}</span>
                  </button>

                  <button
                    type="button"
                    class="rounded-[var(--radius-md)] border p-3 text-left transition focus-visible:shadow-[var(--focus-ring)] focus-visible:outline-none"
                    :class="preferences.stageManager.railEnabled ? 'border-[var(--border-strong)] bg-[var(--active-tab-background)] text-[var(--foreground)]' : 'border-[var(--border)] bg-[var(--surface)] text-[var(--muted-foreground)] hover:border-[var(--border-strong)] hover:text-[var(--foreground)]'"
                    @click="preferences.setStageRailEnabled(!preferences.stageManager.railEnabled)"
                  >
                    <span class="flex items-center justify-between gap-3">
                      <span class="text-sm">{{ t('shell.preferences.stageRail') }}</span>
                      <span class="rounded-full border border-[var(--border)] px-2 py-0.5 text-[10px]">
                        {{ preferences.stageManager.railEnabled ? t('shell.preferences.on') : t('shell.preferences.off') }}
                      </span>
                    </span>
                    <span class="mt-2 block text-[11px] opacity-75">{{ t('shell.preferences.stageRailDescription') }}</span>
                  </button>
                </div>

                <div class="mt-4 rounded-[var(--radius-md)] border border-[var(--border)] bg-[var(--surface)] p-3">
                  <div class="flex items-center justify-between gap-3">
                    <div>
                      <span class="text-sm">{{ t('shell.preferences.fullscreenOverview') }}</span>
                      <p class="mt-1 text-xs text-[var(--muted-foreground)]">{{ t('shell.preferences.fullscreenOverviewDescription') }}</p>
                    </div>
                    <StatusPill :label="t('shell.preferences.desktopOnly')" />
                  </div>
                  <AdminButton
                    class="mt-3 w-full"
                    variant="secondary"
                    :disabled="!preferences.stageManagerDesktopAvailable"
                    @click="preferences.openStageOverview()"
                  >
                    {{ t('shell.preferences.openOverview') }}
                  </AdminButton>
                </div>
              </div>
            </section>
          </div>
        </AdminScrollArea>
      </div>
    </Teleport>
  </div>
</template>
`
}
