import { describe, expect, it } from 'vitest'
import appShellSource from '../AppShell.vue?raw'
import aiAssistantSource from '../AiAssistantFloatingPanel.vue?raw'
import dualColumnSource from '../layouts/DualColumnLayout.vue?raw'
import topHeaderSource from '../layouts/TopHeaderLayout.vue?raw'
import triColumnSource from '../layouts/TriColumnLayout.vue?raw'
import globalPreferencesSource from './GlobalPreferences.vue?raw'
import globalPreferencesTriggerSource from './GlobalPreferencesTrigger.vue?raw'

describe('global preferences shell wiring', () => {
  it('mounts the control center modal once with a prominent top-right app-shell trigger', () => {
    expect(appShellSource).toContain('<GlobalPreferences trigger="none" />')
    expect(appShellSource).toContain('openControlCenter')
    expect(appShellSource).toContain("import GlobalPreferencesTrigger from './preferences/GlobalPreferencesTrigger.vue'")
    expect(appShellSource).toContain('<GlobalPreferencesTrigger')
    expect(appShellSource).toContain('<template #header-actions>')
    expect(triColumnSource).toContain('<slot name="header-actions" />')
    expect(dualColumnSource).toContain('<slot name="header-actions" />')
    expect(topHeaderSource).toContain('<slot name="header-actions" />')
    expect(globalPreferencesSource).toContain("import GlobalPreferencesTrigger from './GlobalPreferencesTrigger.vue'")
    expect(globalPreferencesSource).toContain('<GlobalPreferencesTrigger')
    expect(globalPreferencesTriggerSource).toContain('Settings2')
    expect(globalPreferencesTriggerSource).toContain("import { motion, useReducedMotion } from 'motion-v'")
    expect(globalPreferencesTriggerSource).toContain('global-preferences-trigger')
    expect(globalPreferencesTriggerSource).toContain('global-preferences-trigger__label')
    expect(appShellSource).toContain('controlCenterLabel')
    expect(globalPreferencesTriggerSource).toContain('labelUnits')
    expect(globalPreferencesTriggerSource).toContain('v-for="unit in labelUnits"')
    expect(globalPreferencesTriggerSource).toContain('global-preferences-trigger__glyph')
    expect(globalPreferencesTriggerSource).toContain('<motion.span')
    expect(globalPreferencesTriggerSource).toContain('labelMotionTransition')
    expect(globalPreferencesTriggerSource).toContain('repeat: Infinity')
    expect(globalPreferencesTriggerSource).toContain('repeatDelay')
    expect(globalPreferencesTriggerSource).toContain('duration: 0.72')
    expect(globalPreferencesTriggerSource).toContain('y: [0, -3, 1, 0]')
    expect(globalPreferencesTriggerSource).toContain('rotateX: [0, 18, -6, 0]')
    expect(globalPreferencesTriggerSource).toContain('variant="secondary"')
    expect(globalPreferencesTriggerSource).toContain('size="md"')
    expect(globalPreferencesTriggerSource).toContain('shadow-[var(--card-shadow)]')
    expect(appShellSource).not.toContain('control-center-strip')
    expect(appShellSource).not.toContain('AdminButton')
    expect(appShellSource).not.toContain('Settings2')
    expect(appShellSource).not.toContain('fixed right-4 top-4')
    expect(appShellSource).not.toContain('fixed right-4 top-1/2')
    expect(appShellSource).not.toContain('-translate-y-1/2')
    expect(globalPreferencesTriggerSource).not.toContain('@keyframes')
    expect(globalPreferencesTriggerSource).not.toContain('animation:')
    expect(globalPreferencesTriggerSource).not.toContain('animation-delay')
    expect(globalPreferencesTriggerSource).not.toContain('control-center-title-sweep')
    expect(globalPreferencesTriggerSource).not.toContain('background-clip: text')
    expect(globalPreferencesSource).toContain('preferences.controlCenterOpen')
    expect(globalPreferencesSource).toContain('preferences.setLocale')
    expect(globalPreferencesSource).toContain('shell.preferences.locale')
    expect(globalPreferencesSource).toContain('shell.preferences.displayMode')
    expect(globalPreferencesSource).not.toContain('shell.preferences.modeDensity')
    expect(globalPreferencesSource).toContain('preferences.setStageRailEnabled')
    expect(globalPreferencesSource).toContain('preferences.openStageOverview')
    expect(globalPreferencesSource).toContain('shell.preferences.stageRail')
    expect(globalPreferencesSource).toContain('shell.preferences.fullscreenOverview')
    expect(globalPreferencesSource).toContain('shell.preferences.desktopOnly')
    expect(globalPreferencesSource).not.toContain('setStageManagerPresentationMode')
    expect(globalPreferencesSource).not.toContain('stagePresentationMode')
    expect(globalPreferencesSource).not.toContain('stageModes.sideDock')
    expect(globalPreferencesSource).not.toContain('stageModes.allWindows')
    expect(globalPreferencesSource).toContain('data-layout-preview')
    expect(globalPreferencesSource).toContain('<AdminScrollArea')
    expect(globalPreferencesSource).toContain('as="section"')
    expect(globalPreferencesSource).toContain('max-h-[min(92vh,calc(100vh-2rem))] w-full max-w-5xl overflow-hidden')
    expect(globalPreferencesSource).toContain('sticky top-0')
    expect(globalPreferencesSource).toContain('items-start')
    expect(globalPreferencesSource).not.toContain('flex h-[min(92vh,calc(100vh-2rem))]')
    expect(globalPreferencesSource).not.toContain('max-h-[calc(88vh-92px)]')
    expect(globalPreferencesSource).not.toContain('densityOptions')
    expect(globalPreferencesSource).not.toContain('selectDensity')
    expect(globalPreferencesSource).not.toContain('shell.preferences.density')
    expect(globalPreferencesSource).not.toContain('preferences.setDensity')
    expect(globalPreferencesSource).not.toContain('setStageManagerScrollOverflow')
    expect(globalPreferencesSource).not.toContain('stageManagerScroll')
    expect(globalPreferencesSource).not.toContain('stageScrollDescription')
  })

  it('mounts AI assistance as a floating panel instead of a permanent context rail', () => {
    expect(appShellSource).not.toContain('ContextPanelHost')
    expect(appShellSource).toContain('<AiAssistantFloatingPanel />')
    expect(aiAssistantSource).toContain('preferences.aiAssistantOpen')
    expect(aiAssistantSource).toContain('shell.assistant.title')
    expect(aiAssistantSource).toContain('shell.assistant.provider')
    expect(aiAssistantSource).toContain('shell.assistant.providerConnected')
    expect(aiAssistantSource).toContain('shell.assistant.providerUnavailableMessage')
    expect(aiAssistantSource).toContain('translateRouteTitle(t, route.path')
    expect(aiAssistantSource).toContain('translateRouteDescription(t, route.path')
  })
})
